env:
  browser: true
  es2021: true
extends:
  - eslint:recommended
  - plugin:prettier/recommended
  - plugin:react/recommended
  - plugin:react-hooks/recommended
  - standard-with-typescript
  - plugin:@typescript-eslint/recommended
  - plugin:import/recommended
  - plugin:import/typescript
  - prettier
overrides: []
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaVersion: latest
  sourceType: module
  project:
    - './tsconfig.json'
  tsconfigRootDir: '.'
plugins:
  - react
  - '@typescript-eslint'
rules:
  import/extensions:
    - 'error'
    - js: 'never'
      jsx: 'never'
      ts: 'never'
      tsx: 'never'
  import/prefer-default-export: 'off'
  no-use-before-define: 'off'
  '@typescript-eslint/no-use-before-define': 'off'
  react/jsx-filename-extension:
    - 'error'
    - extensions:
        - '.jsx'
        - '.tsx'
  react/react-in-jsx-scope: 'off'
  no-void:
    - 'error'
    - allowAsStatement: true
  react/no-unknown-property:
    - 2
    -
      ignore:
        - "jsx"

settings:
  import/resolver:
    node:
      extensions:
        - '.js'
        - '.jsx'
        - '.ts'
        - '.tsx'
      paths:
        - 'src'
  react:
    version: "detect"
